config/routes.rb
Rails.application.routes.draw do
  resources :wikis
  devise_for :users

  root to: 'wikis#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role

  def set_default_role
  	role ||= :standard
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = Wiki.all
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user_id = current_user.id

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    # @wiki = Wiki.find(params[:id])
    # authorize @wiki
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>




 <% if user_signed_in? %>
   Signed in as: <strong><%= current_user.email %></strong> | 
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>

   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wikis/_form.html.erb
<%= form_for(wiki) do |f| %>
  <% if wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

<!--   <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form', wiki: @wiki %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wikis</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Private</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= wiki.title %></td>
        <td><%= wiki.body %></td>
        <td><%= wiki.private %></td>
        <td><%= wiki.user %></td>
        <td><%= link_to 'Show', wiki %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form', wiki: @wiki %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @wiki.body %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @wiki.user %>
</p>

<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Back', wikis_path %>